<a href="https://colab.research.google.com/github/KangDongJun-ux/MOBILITY/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D_%EA%B0%95%EC%9D%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EB%B3%B8_%EC%97%B0%EC%8A%B5_1wk_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  파이토치 기본 #

## A. Torch

In [ ]:
import torch

`-` 벡터

In [ ]:
torch.tensor([1,2,3]) # 길이가 3인 벡터

torch.Size([3])

`-` 벡터의 덧셈

In [ ]:
torch.tensor([1,2,3]) + torch.tensor([2,2,2]) # 각 원소끼리 더함.

tensor([3, 4, 5])

`-` 브로드캐스팅

In [ ]:
torch.tensor([1,2,3]) + 2 # 원래는 벡터끼리만 더하기가 가능하지만 이렇게도 허용함. 2 --> torch.tensor([2,2,2]) 처럼 작동하는 것으로 보임.

tensor([3, 4, 5])

##  B. 벡터와 매트릭스

`-` 3 X 2 matrix

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) # [1.2] 하나가 행, [1.2]에 두개의 열이 있음. 즉 이 메트릭스는 3 X 2 행렬임.

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` 3 X 1 matrix = 3 X 1 column vector

In [ ]:
torch.tensor([[1],[2],[3]]) # 열 벡터

tensor([[1],
        [2],
        [3]])

`-` 1 X 2 matrix = 1 X 2 row vertor

In [ ]:
torch.tensor([[1,2]]) # 행 벡터

tensor([[1, 2]])

`-` 더하기

**브로드캐스팅(편한거)**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) - 1 # 1이 torch.tensor([[1,1],[1,1],[1,1]]) 과 같이 작동함.

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-3],[-5]])  # 뒷 항이 torch.tensor([[-1.-1],[-1,-1],[-1,-1]])으로 작동함. 즉 나머지 열을 채움

tensor([[0, 1],
        [0, 1],
        [0, 1]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2]]) # 뒷 항이 torch.tensor([[-1,-2],[-1,-2],[-1,-2]])처럼 작동함.  즉 나머지 행을 채움

tensor([[0, 0],
        [2, 2],
        [4, 4]])

**잘못된 브로드캐스팅**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-3,-5]]) # 행이나 열의 개수가 하나라도 같아야 브로드캐스팅이 되는 듯??

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-2]]) # 행이나 열의 개수가 하나도 안맞으면 브로드캐스팅 안되는 듯??

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

**이상한 것**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-2]) # 3 X 2 matrix 와 크기가 2인 vector의 합이 가능   # 벡터 항이 torch.tensor([[-1,-2]])처럼 작동해서 브로드캐스팅이 가능한 듯??

tensor([[0, 0],
        [2, 2],
        [4, 4]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-3,-5])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

`-` 행렬곱

**정상적인 행렬곱**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1],[2]]) #  3 X 2 @ 2 X 1 = 3 X 1

tensor([[ 5],
        [11],
        [17]])

In [ ]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 1 X 3 @ 3 @ 2 = 1@ 2

tensor([[22, 28]])

**잘모된 행렬곱**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1,2]]) # 3 X 2 @ 1 X 2 = X

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

In [ ]:
torch.tensor([[1],[2],[3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 3 X 1 @ 3 X 2 = X

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x2)

**이상한 것**

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([1,2]) # 행렬과 벡터 곱인데 가능 --> 결과 : 길이가 3인 벡터
                                                                                      # 결과:  각 원소는 각 행과 [1,2]의 내적
                                                                                      # [1,2] * [1,2] = 1*1 + 2*2 = 5

tensor([ 5, 11, 17])

In [28]:
torch.tensor([1,2,3]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 결과: 길이가 2인 벡터
                                                                                         # 결과: 각 원소는 각 열과 [1,2,3]의 내적
                                                                                         # [1.2.3] * [1,3,5] = 1*1 + 2*3  + 3*5 = 22

tensor([22, 28])

## C. transpose, reshape

`-` transpose

In [32]:
torch.tensor([[1,2],[3,4]]).T # 열과 행을 바꿈 대각선을 기준으로 바꿈

tensor([[1, 3],
        [2, 4]])

In [33]:
torch.tensor([[1], [3]]).T # 2 X 1 matrix --> 1 X 2 matrix

tensor([[1, 3]])

In [34]:
torch.tensor([[1,2]]).T # 1 X 2 matrix --> 2 X 1 matrix

tensor([[1],
        [2]])

`-` reshape

**일반적인 사용**

In [35]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [37]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [38]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6)  # 길이가 6인 벡터

tensor([1, 2, 3, 4, 5, 6])

**편한 것**

In [39]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,-1) # 2행으로 맞추고 싶을 때 뒷 열을 -1로 넣어주면 자동으로 열을 맞춰줌.

tensor([[1, 2, 3],
        [4, 5, 6]])

In [40]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1) # 1차원으로 변환(평탄)

tensor([1, 2, 3, 4, 5, 6])

## D. concat, stack $(\star\star\star)$

`-` concat

In [41]:
a = torch.tensor([[1],[3],[5]]) # 3 X 1 matrix
b = torch.tensor([[2],[4],[6]]) # 3 X 1 matrix
torch.concat([a,b], axis = 1) # 3 X 2 matrix  # axis를 지정해서 열로 붙을지 행으로 붙을 지 정할 수 있다.
# concat 은 matrix 기준 가능

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` stack

In [42]:
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
torch.stack([a,b], axis = 1 )
# stack 은 벡터 기준에서 가능

tensor([[1, 2],
        [3, 4],
        [5, 6]])