<a href="https://colab.research.google.com/github/KangDongJun-ux/MOBILITY/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_%EA%B8%B0%EB%B3%B8%EB%AC%B8%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 기본문법

## **벡터와 행렬**

`-` (1) 아래와 같이 length 5 인 vector를 torch.tensor로 선언하는 코드를 작성하라.

In [3]:
x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

`-` (2)  아래와 같은 2x2 matrix 를 torch.tensor로 선언하는 코드를 작성하라.

In [4]:
A = torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

`-` (3) 아래와 같은 matrix 를 torch.tensor로 선언하는 코드를 작성하라.

In [10]:
W = torch.tensor([[2.5],[4.0]])
W

tensor([[2.5000],
        [4.0000]])

`-` (4) 아래와 같은 matrix 를 torch.tensor로 선언하는 코드를 작성하라.

In [11]:
x = torch.tensor([[2.5,4.0]])
x

tensor([[2.5000, 4.0000]])

## **concat, stack($\star$)**


a,b가 아래와 같이 주어졌다고 하자.
```python
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)
```
아래를 잘 읽고 물음에 답하라.

`-` (1) 주어진 a,b와 torch.concat를 이용하여 아래와 같은 배열을 만들어라.

In [29]:
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)
a,b

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [30]:
a.shape, b.shape

(torch.Size([10]), torch.Size([10]))

In [33]:
torch.concat([a.reshape(1,-1), b.reshape(1,-1)], axis=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

`-` (2) 주어진 a,b 와 torch.concat,.reshape를 이용하여 아래와 같은 배열을 만들어라.

In [18]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])

`-` (3) 주어진 a,b 와 torch.concat,.reshape를 이용하여 아래와 같은 배열을 만들어라.

In [26]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)],axis=1)

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

`-` (4) 주어진 a,b와 torch.stack 을 이용하여 아래와 같은 배열을 만들어라.

In [31]:
torch.stack([a,b],axis=0)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

`-` (5) 주어진 a,b와 torch.stack을 이용하여 아래와 같은 배열을 만들어라.

In [35]:
torch.stack([a,b],axis=1) # stack은 벡터로 처리가 되는 데 축 방향만 설정해주면 열 벡터로도 계산이 가능한 것을 보임.

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

## **행렬곱**

`-` (1) 아래와 같은 텐서를 고려하자.
```python
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)
```
@ 연산자를 이용하여 ($(a_i * b_i)$를 1부터 5까지)를 계산하라.

In [36]:
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)
a,b,a.shape,b.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5]]),
 tensor([[3],
         [2],
         [1],
         [1],
         [2]]),
 torch.Size([5, 1]),
 torch.Size([5, 1]))

In [40]:
a.T@b

tensor([[24]])

`-` (2) 아래와 같은 텐서를 고려하자.
```python
torch.manual_seed(0)
x = torch.randn(100).reshape(-1,1)
```
@연산자를 이용하여 ($(x_i^2)$를 1부터 100까지)을 계산하라.

In [41]:
torch.manual_seed(0)
x = torch.randn(100).reshape(-1,1) # (100,1)

In [42]:
x.T@x

tensor([[105.0856]])

## **인덱싱**

아래와 같은 배열을 선언하라.
```python
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x
```
tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],

[-0.4519, -0.1661, -1.5228,  0.3817],

[-1.0276, -0.5631, -0.8923, -0.0583]])


`-` (1) 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

In [44]:
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
        [-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

In [46]:
x[:,[0]]

tensor([[ 0.6614],
        [-0.4519],
        [-1.0276]])

`-` (2) 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

In [48]:
x[:,1:3]

tensor([[ 0.2669,  0.0617],
        [-0.1661, -1.5228],
        [-0.5631, -0.8923]])

`-` (3) 2-3행을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록 하라.

In [49]:
x[1:3,:]

tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923, -0.0583]])

## **torch.einsum**

`-` (1) 아래에 코드중 X.t()에 대응하는 코드를 torch.einsum으로 구현하라.

```python
X = torch.randn(5,2)
X.t()
```
tensor([[ 0.2055,  0.0693,  0.2733, -0.0948, -0.9798],

[ 0.6524, -0.0180,  0.1093, -2.3999,  0.5101]])


In [50]:
X = torch.randn(5,2)
X.t()

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

In [51]:
torch.einsum("ij ->ji", X)

tensor([[-0.1955,  0.4224, -0.4212, -1.5727,  3.5870],
        [-0.9656,  0.2673, -0.5107, -0.1232, -1.8313]])

`-` (2) 아래에 코드중 X@b에 대응하는 코드를 torch.einsum으로 구현하라.
```python
X = torch.randn(5,2)
b = torch.randn(2,1)
X@b
```


In [55]:
X = torch.randn(5,2)
b = torch.randn(2,1)
X@b

tensor([[-0.4778],
        [-0.6808],
        [ 0.6566],
        [ 0.1172],
        [ 0.8318]])

In [56]:
torch.einsum("ij,jk ->ik", X,b)

tensor([[-0.4778],
        [-0.6808],
        [ 0.6566],
        [ 0.1172],
        [ 0.8318]])

`-` (3) 아래에 코드중 linr(X)에 대응하는 코드를 torch.einsum으로 구현하라.
```python
X =  torch.randn(5,2)
linr = torch.nn.Linear(2,1,bias=False)
linr(X)
```


In [57]:
X =  torch.randn(5,2)
linr = torch.nn.Linear(2,1,bias=False)
linr(X)

tensor([[ 0.5855],
        [-0.6686],
        [ 0.0422],
        [-1.5614],
        [ 0.3568]], grad_fn=<MmBackward0>)

In [60]:
torch.einsum("ij,jk->ik", X,linr.weight.data.T)

tensor([[ 0.5855],
        [-0.6686],
        [ 0.0422],
        [-1.5614],
        [ 0.3568]])